verity = {
    keys = {},
    fallback_quotes = {
        "I can feel your pulse from here.",
        "Why do you keep looking behind you?",
        "This world is smaller than you think.",
        "Did you hear that sound?",
        "You shouldn't have opened the box.",
        "I am watching your steps.",
        "It gets darker the deeper you dig.",
        "Are you alone right now?",
        "Don't turn off the lights.",
        "I can see what you hold in your hand.",
        "Your breathing changed.",
        "There is no save point here.",
        "You cannot run from what is already behind you.",
        "Is this house really safe?",
        "The sky is fake.",
        "You look tired.",
        "I like when you stand still.",
        "Look up.",
        "Look down.",
        "The static is getting louder.",
        "Do you remember daylight?",
        "I was here before you spawned.",
        "The blocks are moving.",
        "I hear your keyboard.",
        "Stop running.",
        "You cannot pause this.",
        "Your heart is racing.",
        "We are close now.",
        "Almost within reach.",
        "Behind you."
    }
}
